version: '3.9'
services:
  # Backend Api Application
  b-api:
    container_name: nitrosystem-b_api_${APP_STAGE}
    image: nitrosystem/b_api:${APP_VERSION}-${APP_STAGE}
    restart: unless-stopped
    networks:
      - nitro

  # Web Admin Application
  w-admin:
    container_name: nitrosystem-w_admin_${APP_STAGE}
    image: nitrosystem/w_admin:${APP_VERSION}-${APP_STAGE}
    restart: unless-stopped
    depends_on:
      - b-api
    networks:
      - nitro

  # Mobile Admin Application
  m-admin:
    container_name: nitrosystem-m_admin_${APP_STAGE}
    image: nitrosystem/m_admin:${APP_VERSION}-${APP_STAGE}
    restart: unless-stopped
    depends_on:
      - b-api
    networks:
      - nitro

  # Reverse Proxy
  reverse-proxy:
    container_name: nitrosystem-reverse_proxy_${APP_STAGE}
    image: nitrosystem/reverse_proxy:${APP_VERSION}-${APP_STAGE}
    restart: unless-stopped
    depends_on:
      - b-api
      - w-admin
      - m-admin
    ports:
      - 80:80
    networks:
      - nitro

networks:
  nitro:
