# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Check Commit Message

on: [pull_request, push]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      # Get checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Check commits message
      - name: Check commits message
        uses: wagoid/commitlint-github-action@v5 # cspell:ignore wagoid
