# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# cspell:ignore buildx

name: Docker

on:
  push:
    branches: [staging]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Get checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Build
      - name: Build and push Build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: nitrosystem/staging_build:latest
          target: dist
          build-args: |
            stage=staging

      # Build and push Backend Api
      - name: Build and push Backend Api
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: nitrosystem/staging_b_api:latest
          target: backend
          build-args: |
            app=b-api
            stage=staging

      # Build and push Admin Web
      - name: Build and push Admin Web
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: nitrosystem/staging_w_admin:latest
          target: frontend
          build-args: |
            app=w-admin
            stage=staging

      # Build and push Admin Mobile
      - name: Build and push Admin Mobile
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: nitrosystem/staging_m_admin:latest
          target: frontend
          build-args: |
            app=m-admin
            stage=staging

      # Login to Heroku Registry
      - name: Login to Heroku Registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_STAGING_USERNAME }}
          password: ${{ secrets.HEROKU_STAGING_API_KEY }}

      # Build and push Backend Api
      - name: Build and push Backend Api
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.heroku.com/ns-staging_b_api/web:latest
          target: backend
          build-args: |
            app=b-api
            stage=staging

      # Build and push Admin Web
      - name: Build and push Admin Web
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.heroku.com/ns-staging_w_admin/web:latest
          target: frontend
          build-args: |
            app=w-admin
            stage=staging

      # Build and push Admin Mobile
      - name: Build and push Admin Mobile
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.heroku.com/ns-staging_m_admin/web:latest
          target: frontend
          build-args: |
            app=m-admin
            stage=staging
