# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# cspell:ignore buildx getsentry sourcemaps gonuit

name: Publish a new release

on:
  push:
    branches: [staging]

jobs:
  # Run Semantic Release only on staging branch
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      # Get checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Node js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'

      # Run Semantic Release
      - name: Semantic Release
        run: |
          npm i -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
          GIT_AUTHOR_NAME: Omar Elsayed
          GIT_AUTHOR_EMAIL: omar-alsayed@syscodeia.ae
          GIT_COMMITTER_NAME: Omar Elsayed
          GIT_COMMITTER_EMAIL: omar-alsayed@syscodeia.ae

      # # Checkout Develop
      # - name: Checkout Develop
      #   uses: actions/checkout@v3
      #   with:
      #     ref: develop

      # # Pull From `Staging` to `Develop`
      # - name: Pull From `Staging` to `Develop`
      #   run: |
      #     git pull origin staging
      #     git push

  # Publish Sonar Release
  sonar:
    runs-on: ubuntu-latest
    needs: semantic-release
    steps:
      # Get checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Get Package.json Version
      - name: Get Package.json Version
        id: package
        uses: martinbeentjes/npm-get-version-action@main # cspell:ignore martinbeentjes

      # Extract Environments
      - name: Extract environments
        shell: bash # cspell:ignore elif
        run: |
          ls
          cat package.json
          echo ${{ steps.package.outputs.current-version }}
