# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish Release & Create Change Log

on:
  push:
    branches: [master]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      # Get checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'

      # Install Dependencies
      - name: Install dependencies 🔧
        run: |
          npm i -g npm@latest
          npm ci

      # Npm Run Test
      - name: Run Test
        run: npm run test

      # Build application
      - name: Run Build
        run: npm run build

      # Install Semantic Release Global
      - name: Install Semantic Release Global
        run: npm i -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec

      # Run Semantic Release
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GIT_AUTHOR_NAME: ${{secrets.AUTHOR_NAME}}
          GIT_AUTHOR_EMAIL: ${{secrets.AUTHOR_EMAIL}}
          GIT_COMMITTER_NAME: ${{secrets.AUTHOR_NAME}}
          GIT_COMMITTER_EMAIL: ${{secrets.AUTHOR_EMAIL}}

      # Checkout Develop
      - name: Checkout Develop
        uses: actions/checkout@v3
        with:
          ref: develop

      # Pull From `Master` to `Develop`
      - name: Pull From `Master` to `Develop`
        run: |
          git pull origin master
          git push

      # Checkout Staging
      - name: Checkout Staging
        uses: actions/checkout@v3
        with:
          ref: staging

      # Pull From `Master` to `Staging`
      - name: Pull From `Master` to `Staging`
        run: |
          git pull origin master
          git push
