# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sonar Cloud

on:
  push:
    branches: [master, staging, develop]
  pull_request:
    branches: [master, staging, develop]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # Get checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Get Package.json Version
      - name: Get Package.json Version
        id: package
        uses: martinbeentjes/npm-get-version-action@main # cspell:ignore martinbeentjes

      # Extract Environments
      - name: Extract environments
        shell: bash # cspell:ignore elif
        run: |
          version="latest"
          if [ $branch != "develop" ]; then version=${{ steps.package.outputs.current-version }}; fi
          sed -i -e 's/$APP_VERSION/'"$version"'/g' "./sonar-project.properties"

      # Run Sonarqube
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master # cspell:ignore sonarcloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
