# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sonar Cloud

on:
  push:
    branches: [develop, master, staging]
  pull_request:
    branches: [develop, master, staging]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # Get checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Run Sonarqube
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master # cspell:ignore sonarcloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
